# Generated by Django 4.1.2 on 2022-12-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='product',
        ),
    ]
